### ISSUE TITLE
[Question] Do uploaded photos count toward your storage quota?

### ISSUE THREAD

**Issue by ammgws** [simonedegiacomi/gphotosuploader#11]
As per the title. When uploading through the official channels (photos.google.com, Backup and Sync, Google Photos app) you can have unlimited storage by allowing Google to resize your photos/videos. Have you been able to reverse engineer that part of the upload API as well?

**Comment by simonedegiacomi** [comment]
Hi!
It should work, just make sure you've selected the upload option that resizes your photos on the settings page of the web interface.
If you are having some troubles feel free to write them down here, otherwise we can close this issue.

**Comment by ammgws** [comment]
Thanks for the response. I will check this within the next couple of weeks.

**Comment by andrea689** [comment]
I have tested this. I have upload a 17MP photo and has been resized to 16MP without consuming quota. Good job guys!

**Comment by ammgws** [comment]
OK I have finally gotten around to testing and it looks to be working fine. (Tested with some mp4 files)
