### ISSUE TITLE
Selenium WebDrivers Dependancy

### ISSUE THREAD

**Issue by suntong** [simonedegiacomi/gphotosuploader#20]
It wasn't 100% clear in Readme -- So, 

The Selenium WebDrivers is only needed for authentication to create/update that JSON file, right? 

I.e., if I'm able to authenticate using the Chrome browser extension, I don't need it for the normal uploading, right? 

thx

**Comment by simonedegiacomi** [comment]
Yes, you don't need the Selenium WebDriver to use the tool/library.
