### ISSUE TITLE
two different gphoto accounts

### ISSUE THREAD

**Issue by ihartaras** [simonedegiacomi/gphotosuploader#22]
Thanks for tool!
Is it possible to synchronize two different folders with two different gphoto accounts in the same time?

**Comment by simonedegiacomi** [comment]
Yes, you can run multiple instances of the tool, but you need to take care of the auth file.

For example,  if you have a folder A that you want to upload to account 1 and a folder B that you want to upload to account 2, you can use something like this:

```bash
go run main.go --auth auth-a.json --upload ~/images/A
go run main.go --auth auth-b.json --upload ~/images/B
```

You can also use two different files for the uploaded list (using the --uploadedList argument) but it's not necessary.
