### ISSUE TITLE
does it upload subdirectories on watched directory atomatically ?

### ISSUE THREAD

**Issue by kurokirasama** [simonedegiacomi/gphotosuploader#24]
or we need to add them individually ?

**Comment by simonedegiacomi** [comment]
It should automatically watch subfolders if you use the "--watchRecursively" command line argument.

**Comment by kurokirasama** [comment]
what about upload recursively?

**Comment by simonedegiacomi** [comment]
When folders are watched recursively files will be uploaded when added to the subfolders. At the moment there isn't an option to recursively upload existing files, you need to specify them. Maybe a flag to upload recursively existing files would be useful?

**Comment by simonedegiacomi** [comment]
When watching folders recursively new files added to the subfolders will be uploaded.
At the moment there isn't an option to recursively upload existing files, you need to specify them manually. Perhaps a flag to recursively upload existing files could be useful?

**Comment by kurokirasama** [comment]
yes, that would be really useful. Thanks!

**Comment by simonedegiacomi** [comment]
Sorry, I was wrong.  The [function](https://golang.org/pkg/path/filepath/#Walk) used to walk the file system to search files to upload is already recursive. This means that if you have a folder with a subfolder with an image (ex: a/b/file.jpg) that file will be uploaded.

**Comment by kurokirasama** [comment]
Cool! 😎

**Comment by kurokirasama** [comment]
Cool! 😎
