### ISSUE TITLE
chromedriver doesn't ask for browser

### ISSUE THREAD

**Issue by kurokirasama** [simonedegiacomi/gphotosuploader#25]
after running chromedriver i got stuck in:

```
Starting ChromeDriver 2.36 (0) on port 9515
Only local connections are allowed.
```

**Comment by simonedegiacomi** [comment]
You don't have to insert the browser name into the chromedriver, but only in the tool.
After you've started the chromedriver did you insert the browser name and chromedriver address in the tool? The chromedriver is supposed to listen incoming connections and wait, so it's normal that the output of the chromedriver doesn't change until the tool asks the chromedriver to open the login page.

**Comment by kurokirasama** [comment]
I see, thanks. It worked now!
