### ISSUE TITLE
Upload error can't get an upload url.

### ISSUE THREAD

**Issue by shindycham01** [simonedegiacomi/gphotosuploader#29]
Hi, I have just discovered this tool and wanted to test it out but unfortunately an error message faced me:

2018/08/27 19:15:48 Auth file loaded, checking validity ...
2018/08/27 19:15:59 Auth file seems to be valid
2018/08/27 19:15:59 Getting a new At token ...
2018/08/27 19:15:59 At token taken
2018/08/27 19:15:59 Upload error: Error with '/home/user/pictures/1.jpg': can't get an upload url

I hope one can help me out. Thanks.

**Comment by MikeLund** [comment]
This is typically an error when your account has been "blacklisted" by Google for uploading too many files. Try with a different account and see if it works better.

**Comment by shindycham01** [comment]
The error disappeared. Thanks
