### ISSUE TITLE
Show created album ID in log

### ISSUE THREAD

**Issue by GaPhi** [simonedegiacomi/gphotosuploader#36]
I need to get back the created album ID.

The solution I have implemented is to display the albumID in the log.
Here is the the patch: [diff.txt](https://github.com/simonedegiacomi/gphotosuploader/files/3061259/diff.txt)

Can you update github with it?
I have not succeeded in doing it myself (I am new in github.com).

Thank you!

**Comment by simonedegiacomi** [comment]
Hi, thank you for your patch!
I've applied the patch and pushed the changes.

A suggestion: the next time you'll want to submit a change to a repository, try to create a pull request (feel free to ask questions if you're in doubt ;-).

To create a pull request you need to:
- Fork the repository;
- Edit the code on the forked repository;
- Create the pull request ([this is the Github guide](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork));
