### ISSUE TITLE
--albumName with --maxConcurrent >1

### ISSUE THREAD

**Issue by GaPhi** [simonedegiacomi/gphotosuploader#37]
With the following command line, several albums are created with the same name.
`gphotosuploader --albumName "New album name" --upload toTransfer/ --maxConcurrent 4`

This is probably due to the parallel threads all creating a new Album (and several albumId) without any mutex for this album creation operation.

The command-line workaround, for now, is to set maxConcurrent to 1 when creating a new album and set it to 4 with an existing albumId.

**Comment by GaPhi** [comment]
Fix is available in my pull request. Hope I have done it in the right way...
Note that I had to change the import section to use my repository for utils/ and api/.

**Comment by simonedegiacomi** [comment]
Thank you for the pull request!
I've accepted it but changed the path of the imports to use again this repository.

(I've done a quick search and [this](https://stackoverflow.com/a/29161911) seems to be a good solution for the problem of the import)
