### ISSUE TITLE
OAuth failed on first start

### ISSUE THREAD

**Issue by greensea** [simonedegiacomi/gphotosuploader#39]
1. I use `gphotos-uploader-cli init` to generate config file.
2. Then I change the  account to my gmail account in config file.
3. Run `gphotos-uploader-cli`, it take me to google OAuth page, but the page throw an error:

```
400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, http://localhost:38373, does not match the ones authorized for the OAuth client.
```
So I am unable to get token, is it any way to do OAuth manually?

**Comment by simonedegiacomi** [comment]
Hi, I think you're referring to [this](https://github.com/gphotosuploader/gphotos-uploader-cli) project ;-)

The tool on this repository doesn't use the Google Photos API, therefore it doesn't authenticate using OAuth.

**Comment by greensea** [comment]
Oh my fault.
I am closing this issue, sorry.
