### ISSUE TITLE
Timestamp is wrong

### ISSUE THREAD

**Issue by nmrshll** [simonedegiacomi/gphotosuploader#4]
Timestamp in the upload options is wrong, it should be multiplied by 1000.

At the moment in the library I'm just doing this to fix it :

```
options, err := api.NewUploadOptionsFromFile(file)
if err != nil {
	return err
}
options.Timestamp = options.Timestamp * 1000
```

But I guess this should be in the library directly. 

Correct me if I'm wrong or if this works well in some cases but not for all files.

By the way, how can I contribute ? Just fork and create pull requests ? I quite like your project so far, and I can see a few ways I would like to change it.

**Comment by simonedegiacomi** [comment]
You're right, I didn't notice it because i was uploading images with metadata, so i agree that the timestamp should always be multiplied.

You can contribute forking and creating pull requests, thank you!

**Comment by nmrshll** [comment]
Here's a small PR, more coming
